FROM ghcr.io/cyber-dojo-languages/clojure:9a28837
LABEL maintainer=frederic.merizen@soft-xki.com
LABEL maintainer=jon@jaggersoft.com

ENV MIDJE_COLORIZE=false
ENV NO_COLOR=1

COPY project.clj /tmp

RUN cd /tmp \
 && lein deps \
 && lein midje --help \
 && chown -R sandbox:sandbox /.m2

